Book feature test
thainguyencoffee/bookstore-datn pull request #8
Opened 2024-07-21 18:51 UTC by nongtiensonpro

2024-07-21 18:58 UTC, thainguyencoffee requested changes

2024-07-21 18:58 UTC, thainguyencoffee commented on backend/src/main/java/com/bookstore/backend/books/BookService.java
> +    public Book addBook(BookCreateDto book) {
Cần có @Transactional ở đây nữa

2024-07-21 18:58 UTC, thainguyencoffee commented on backend/src/main/java/com/bookstore/backend/books/controller/BookController.java
> +@RequestMapping(path = "/api/books")
thiếu producers = MediaType.APPLICATION_JSON_VALUE

2024-07-21 18:58 UTC, thainguyencoffee commented on backend/src/main/java/com/bookstore/backend/books/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
HttpStatus.NO_CONTENT

2024-07-21 19:07 UTC, thainguyencoffee approved these changes

2024-07-21 19:07 UTC, thainguyencoffee approved these changes

2024-07-22 04:03 UTC, ngadeptrai1 commented on backend/src/main/java/com/bookstore/backend/books/controller/BookController.java
> +    public Page<Book> getAllBooks(Pageable pageable) {
return dto

2024-07-22 04:04 UTC, thainguyencoffee commented on backend/src/main/java/com/bookstore/backend/books/controller/BookController.java
> +    public Page<Book> getAllBooks(Pageable pageable) {
return dto?. ông sơn đang return domain model có gì sai

2024-07-22 04:04 UTC, ngadeptrai1 commented
ok

2024-07-22 04:08 UTC, ngadeptrai1 commented on backend/src/main/java/com/bookstore/backend/books/controller/BookController.java
> +    public Page<Book> getAllBooks(Pageable pageable) {
ok

2024-07-22 04:18 UTC, ngadeptrai1 approved these changes

2024-07-22 05:16 UTC, merged